// Generated by CoffeeScript 1.8.0
var docpadConfig,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

docpadConfig = {
  logLevel: 10,
  logger: true,
  templateData: {
    site: {
      url: "http://website.com",
      oldUrls: ['www.website.com', 'website.herokuapp.com'],
      title: "Your Website",
      description: "When your website appears in search results in say Google, the text here will be shown underneath your website's title.",
      keywords: "place, your, website, keywoards, here, keep, them, related, to, the, content, of, your, website",
      author: "Your Name",
      email: "your@email.com",
      copyright: "© Your Company 2013"
    },
    getPreparedTitle: function() {
      if (this.document.title) {
        return "" + this.document.title + " | " + this.site.title;
      } else {
        return this.site.title;
      }
    },
    getPreparedDescription: function() {
      return this.document.description || this.site.description;
    },
    getPreparedKeywords: function() {
      return this.site.keywords.concat(this.document.keywords || []).join(', ');
    }
  },
  collections: {
    pages: function(database) {
      return database.findAllLive({
        pageOrder: {
          $exists: true
        }
      }, [
        {
          pageOrder: 1,
          title: 1
        }
      ]);
    },
    posts: function(database) {
      return database.findAllLive({
        relativeOutDirPath: 'posts'
      }, [
        {
          date: -1
        }
      ]);
    }
  },
  events: {
    serverExtend: function(opts) {
      var docpad, latestConfig, newUrl, oldUrls, server;
      server = opts.server;
      docpad = this.docpad;
      latestConfig = docpad.getConfig();
      oldUrls = latestConfig.templateData.site.oldUrls || [];
      newUrl = latestConfig.templateData.site.url;
      return server.use(function(req, res, next) {
        var _ref;
        if (_ref = req.headers.host, __indexOf.call(oldUrls, _ref) >= 0) {
          return res.redirect(301, newUrl + req.url);
        } else {
          return next();
        }
      });
    }
  }
};

module.exports = docpadConfig;
